FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN mkdir -p heap-snapshots cpu-profiles

ENV NODE_OPTIONS="--max-old-space-size=1000 --expose-gc"

EXPOSE 3000 9229

CMD ["yarn", "start:debug"]