apiVersion: v1
data:
  allow-snippet-annotations: 'true'
  # Set to true for HTTP2
  enable-http2: 'true'
  hsts: 'false'
  use-http2: 'true'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
